#!/usr/bin/env bash
":" //# comment; exec /usr/bin/env node --input-type=module - "$@" < "$0"

import { exec } from 'child_process';
new Promise((res,rej)=>{
    exec('ps aux |  grep "nw ."', (error, stdout, stderr) => {
        if (error || stderr) {
            rej(error);
        }
        const nwjsProcess = stdout.split('\n')[0].replace(/\s\s+/g, ' ')
        const nwjsProcessPid = nwjsProcess.indexOf('grep') === -1 ? nwjsProcess.split(' ')[1] : rej(nwjsProcess);
        res(exec(`kill -9 ${nwjsProcessPid}`));
    });
}).catch(console.log);